//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomTrip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        public decimal ID { get; set; }
        public string EVENT_NAME { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE_FIN { get; set; }
        public Nullable<double> LONGITUDE_FIN { get; set; }
        public string TYPE_EVENEMENT { get; set; }
        public string DESCRIPTIF { get; set; }
        public string URL_PHOTO { get; set; }
        public string ADRESSE { get; set; }
        public string WEBSITE { get; set; }
        public System.Data.Entity.Spatial.DbGeography localisation { get; set; }
    }
}
